<a href="https://colab.research.google.com/github/juanmvalencia1-lgtm/Ejercicios-en-clase-/blob/main/Practica_3_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1) Crea una matriz de 3 x 3 con todos los valores true

import numpy as np

matriz = np.full((3, 3), True)

print(matriz)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# Reemplace todos los numeros impares por -1

np.array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:

help(np.reshape)


Help on _ArrayFunctionDispatcher in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.

    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
     

In [ ]:
# Convertir un array de 1D en uno de 2D con dos filas con la misma cantidad de elementos
# Input:

arr = np.arange(16)

np.reshape(arr, (2, -1))



array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
# Convierte los vectores fila a y b en un vector columna (Apila verticalmente los vectores a y b)
# Input
# ayuda: investigar las funciones np.vstack , np.hstack

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)



print (a)
print (b)

np.vstack((a, b)).reshape (1,-1).T
#np.hstack((a, b))


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [ ]:
# Identifica los elementos iguales en a y b
#Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print (a)
print (b)

print (a[np.where (a == b)])

# ayuda: investigar la funcion np.where

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]
[2 2 4 4]


In [ ]:
# Intercambiar las columnas 1 y 2 en el array arr

arr = np.arange(9).reshape(3,3)
arr

arr= arr[:,[2,0,1]]
arr


array([[2, 0, 1],
       [5, 3, 4],
       [8, 6, 7]])

In [4]:
#librearia que contiene el conjunto de tados llamados iris
from sklearn.datasets import load_iris

#utilizamos la funcion load_iris() para cargar los datos
dataset = load_iris()

#Inspecciones un poco los datos , tenga encuenta que los datos vienen en forma de diccionario
dataset.keys()

#dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

#veamos la descripcion del data set
dataset['DESCR']

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 

In [5]:

#veamos el nombre de las caracteristicas
dataset['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
#veamos las etiquetas
dataset['filename']


'iris.csv'

In [8]:
#separemos los datos
X = dataset['data'][: , [0,1]]

In [9]:
print (X)

[[5.1 3.5]
 [4.9 3. ]
 [4.7 3.2]
 [4.6 3.1]
 [5.  3.6]
 [5.4 3.9]
 [4.6 3.4]
 [5.  3.4]
 [4.4 2.9]
 [4.9 3.1]
 [5.4 3.7]
 [4.8 3.4]
 [4.8 3. ]
 [4.3 3. ]
 [5.8 4. ]
 [5.7 4.4]
 [5.4 3.9]
 [5.1 3.5]
 [5.7 3.8]
 [5.1 3.8]
 [5.4 3.4]
 [5.1 3.7]
 [4.6 3.6]
 [5.1 3.3]
 [4.8 3.4]
 [5.  3. ]
 [5.  3.4]
 [5.2 3.5]
 [5.2 3.4]
 [4.7 3.2]
 [4.8 3.1]
 [5.4 3.4]
 [5.2 4.1]
 [5.5 4.2]
 [4.9 3.1]
 [5.  3.2]
 [5.5 3.5]
 [4.9 3.6]
 [4.4 3. ]
 [5.1 3.4]
 [5.  3.5]
 [4.5 2.3]
 [4.4 3.2]
 [5.  3.5]
 [5.1 3.8]
 [4.8 3. ]
 [5.1 3.8]
 [4.6 3.2]
 [5.3 3.7]
 [5.  3.3]
 [7.  3.2]
 [6.4 3.2]
 [6.9 3.1]
 [5.5 2.3]
 [6.5 2.8]
 [5.7 2.8]
 [6.3 3.3]
 [4.9 2.4]
 [6.6 2.9]
 [5.2 2.7]
 [5.  2. ]
 [5.9 3. ]
 [6.  2.2]
 [6.1 2.9]
 [5.6 2.9]
 [6.7 3.1]
 [5.6 3. ]
 [5.8 2.7]
 [6.2 2.2]
 [5.6 2.5]
 [5.9 3.2]
 [6.1 2.8]
 [6.3 2.5]
 [6.1 2.8]
 [6.4 2.9]
 [6.6 3. ]
 [6.8 2.8]
 [6.7 3. ]
 [6.  2.9]
 [5.7 2.6]
 [5.5 2.4]
 [5.5 2.4]
 [5.8 2.7]
 [6.  2.7]
 [5.4 3. ]
 [6.  3.4]
 [6.7 3.1]
 [6.3 2.3]
 [5.6 3. ]
 [5.5 2.5]
 [5.5 2.6]

In [23]:
import numpy as np

In [13]:
matriz= X

In [25]:
np.max(matriz, axis=0)  # Devuelve el máximo de cada fila


array([7.9, 4.4])

In [26]:
np.min(matriz, axis=1)  # Devuelve el minimo de de cada columna

array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
       3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       3.4, 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.6, 3. ,
       3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3. , 3.8, 3.2, 3.7, 3.3, 3.2, 3.2,
       3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 2.8, 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 2.6, 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3.8, 2.8, 2.8, 2.6, 3. , 3.4, 3.1, 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, 3. , 2.5, 3. , 3.4, 3. ])

In [27]:
max_global = np.max(matriz)
print("Máximo de toda la matriz:", max_global)

Máximo de toda la matriz: 7.9


In [29]:
min_global = np.min(matriz)
print("minimo de toda la matriz:", min_global)

minimo de toda la matriz: 2.0


In [ ]:
#Obtenga el valor medio, la mediana, la moda y la desviacion estandar para cada una de las caracteristicas ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

In [31]:
# X = pd.DataFrame(data=iris.data, columns=iris.feature_names)


In [35]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from scipy import stats


In [ ]:
#librearia que contiene el conjunto de tados llamados iris
#from sklearn.datasets import load_iris

#utilizamos la funcion load_iris() para cargar los datos
#dataset = load_iris()

In [40]:
iris = load_iris()  # Carga el dataset
df = pd.DataFrame(data=dataset.data, columns=dataset.feature_names)


In [42]:
# Media
media = df.mean()

# Mediana
mediana = df.median()

# Moda (puede haber más de una)
moda = df.mode().iloc[0]  # Tomamos la primera fila

# Desviación estándar
desviacion = df.std()

print("Media:\n", media)
print("\nMediana:\n", mediana)
print("\nModa:\n", moda)
print("\nDesviación estándar:\n", desviacion)


Media:
 sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

Mediana:
 sepal length (cm)    5.80
sepal width (cm)     3.00
petal length (cm)    4.35
petal width (cm)     1.30
dtype: float64

Moda:
 sepal length (cm)    5.0
sepal width (cm)     3.0
petal length (cm)    1.4
petal width (cm)     0.2
Name: 0, dtype: float64

Desviación estándar:
 sepal length (cm)    0.828066
sepal width (cm)     0.435866
petal length (cm)    1.765298
petal width (cm)     0.762238
dtype: float64


In [ ]:
#Para cada una de las caracteristicas identifique:
# la cantidad de valores mayores a las medias
# Extraiga los cuartiles de una de las variables (Recuerde que los cuartiles se calculan con los datos ordenados)

In [45]:
media = df.mean()

# Calcula los cuartiles
cuartiles = df.quantile([0.25, 0.5, 0.75])